export interface CarouselProduct {
  id: number;
  number: string;
  name: string;
  subtitle: string;
  price: string;
  material: string;
  fit: string;
  origin: string;
  image: string;
}

export const newArrivals: CarouselProduct[] = [
  {
    id: 1,
    number: "001",
    name: "OXFORD STRIPE SHIRT",
    subtitle: "120s Egyptian Cotton Oxford",
    price: "₹29,900",
    material: "120s Egyptian long-staple cotton",
    fit: "Relaxed tuck-in silhouette",
    origin: "Handcrafted in Portugal",
    image: "/images/product-jacket.png",
  },
  {
    id: 2,
    number: "002",
    name: "LINEN NATURAL CAMP",
    subtitle: "8oz European Linen",
    price: "₹23,200",
    material: "European flax 8oz plain weave",
    fit: "Camp collar relaxed",
    origin: "Handcrafted in Portugal",
    image: "/images/product-jeans.png",
  },
  {
    id: 3,
    number: "003",
    name: "MOTHER-OF-PEARL BUTTON SET",
    subtitle: "Hand-polished Shell Buttons",
    price: "₹9,900",
    material: "Hand-polished nacre shell",
    fit: "Universal 4-hole 15mm",
    origin: "Sourced in Philippines",
    image: "/images/product-hardware.png",
  },
  {
    id: 4,
    number: "004",
    name: "CHAMBRAY WORK SHIRT",
    subtitle: "7oz Cone Mills Chambray",
    price: "₹19,900",
    material: "7oz organic Cone Mills chambray",
    fit: "Classic utility fit",
    origin: "Handcrafted in Portugal",
    image: "/images/product-jacket.png",
  },
  {
    id: 5,
    number: "005",
    name: "SASHIKO BORO OVERSHIRT",
    subtitle: "Hand-stitched Sashiko Weave",
    price: "₹15,900",
    material: "Indigo-dyed heavy sashiko weave",
    fit: "Relaxed workshirt fit",
    origin: "Handcrafted in Portugal",
    image: "/images/product-jeans.png",
  },
  {
    id: 6,
    number: "006",
    name: "NAAMI DRESS SHIRT",
    subtitle: "100s Sea Island Cotton Poplin",
    price: "₹34,900",
    material: "100s Sea Island cotton poplin",
    fit: "Slim spread collar",
    origin: "Handcrafted in Portugal",
    image: "/images/product-jacket.png",
  },
  {
    id: 7,
    number: "007",
    name: "GURKHA COLLAR SHIRT",
    subtitle: "10oz Khadi Cotton",
    price: "₹12,500",
    material: "10oz handspun khadi cotton",
    fit: "Gurkha mandarin collar",
    origin: "Assembled in India",
    image: "/images/product-hardware.png",
  },
];

export const bestsellers: CarouselProduct[] = [
  {
    id: 11,
    number: "011",
    name: "TUXEDO BANDED SHIRT",
    subtitle: "80s Pima Poplin",
    price: "₹24,000",
    material: "80s Superfine pima poplin",
    fit: "Banded collar slim",
    origin: "Handcrafted in Portugal",
    image: "/images/product-jeans.png",
  },
  {
    id: 12,
    number: "012",
    name: "NAAMI KURTA SHIRT",
    subtitle: "Chanderi Silk-Cotton",
    price: "₹43,000",
    material: "Double-layered pure Chanderi silk-cotton",
    fit: "Traditional kurta cut",
    origin: "Handcrafted in India",
    image: "/images/product-jacket.png",
  },
  {
    id: 13,
    number: "013",
    name: "EVERYDAY CHAMBRAY",
    subtitle: "8oz Organic Chambray",
    price: "₹14,900",
    material: "8oz organic cotton chambray",
    fit: "Traditional utility cut",
    origin: "Assembled in Portugal",
    image: "/images/product-hardware.png",
  },
  {
    id: 14,
    number: "014",
    name: "HAORI OVERSHIRT",
    subtitle: "Japanese Shuttle-loom Cotton",
    price: "₹31,500",
    material: "10oz raw Japanese shuttle-loom cotton",
    fit: "Haori collar relaxed drape",
    origin: "Handcrafted in Japan",
    image: "/images/product-jacket.png",
  },
  {
    id: 15,
    number: "015",
    name: "NAAMI HENLEY SHIRT",
    subtitle: "14.5oz Slub Cotton",
    price: "₹28,200",
    material: "14.5oz slub cotton",
    fit: "Boxy henley placket",
    origin: "Handcrafted in Portugal",
    image: "/images/product-jacket.png",
  },
  {
    id: 16,
    number: "016",
    name: "STONEWASH POPLIN",
    subtitle: "Washed Shuttle-loom",
    price: "₹25,600",
    material: "13.5oz washed shuttle-loom cotton",
    fit: "Easy straight fit",
    origin: "Finished in Portugal",
    image: "/images/product-jeans.png",
  },
  {
    id: 17,
    number: "017",
    name: "NAAMI COLLAR STAY SET",
    subtitle: "Sterling Silver",
    price: "₹11,600",
    material: "Sterling silver stays",
    fit: "Universal shirt sizing",
    origin: "Cast in Japan",
    image: "/images/product-hardware.png",
  },
];

export const allProducts = [...newArrivals, ...bestsellers];
